### ISSUE TITLE
[Multiple LS Clients] Rename adds extra characters when converting from camelCase to Constant Case

### ISSUE THREAD

**Issue by johmsalas** [johmsalas/text-case.nvim#107]
LSP Rename adds extra characters 

**Reproduction Steps:**

- In the [sample file](https://github.com/johmsalas/text-case.nvim/blob/main/samples/component.jsx), locate the cursor on the variable currentStep in the 5th line
- `gaN`
- The new name of the variable is `CURRENT_STEPP`, expected result is `CURRENT_STEP`

Also failing for Telescope LSP renaming
`gan` works fine.

**Comment by johmsalas** [comment]
Found out this happens when there are multiple attached LS clients and there is a change in the string length. For example when converting from fooBar to FOO_BAR, there is one extra character in the result

**Comment by peterfication** [comment]
Setting up different language servers in the tests seems a lot though. Which language servers were running on your machine when you found this bug?

**Comment by johmsalas** [comment]
@peterfication this is an example of how to mock the LSP clients 
https://github.com/johmsalas/text-case.nvim/blob/68a0a58996d58ed36fbfc945821a34e7b953d12a/tests/textcase/lsp/error_handling_no_lsp_spec.lua#L92

**Comment by johmsalas** [comment]
The difference between buf_request and buf_request_all is buf_request is called n times, where n is the amount of clients. On the other hand, buf_request_all is called only once, and all the results are passed in the callback. To mock the buf_request_all, we'd call the callback once and pass different sets of results according to the behavior we'd want to mock

**Comment by peterfication** [comment]
Ah nice, makes sense 👍
