### ISSUE TITLE
[Feature request] add default mappings to the Telescope prompt.

### ISSUE THREAD

**Issue by avmunm** [johmsalas/text-case.nvim#128]
Basically when opening the telescope prompt, would it be possible to add the default mappings next to the selection?
I think this might help me (and others) learn the mappings, while having the convenience of using them form Telescope.

**Comment by avmunm** [comment]
basically something like this:
![image](https://github.com/johmsalas/text-case.nvim/assets/152485151/0b0994ef-d089-4655-9aec-9c1e78b88f6a)

**Comment by peterfication** [comment]
mhh it's an interesting idea. But which-key provides this already. Do you use which-key?

**Comment by avmunm** [comment]
I used it previously, but did not really like it on all the time. 
I might turn it on again, it's a fair point. No need to add unnecessary complexity for my niche use case to be fair.

**Comment by peterfication** [comment]
Alright. Closing this ticket then.
