### ISSUE TITLE
Make another version of TextCaseStartReplacingCommand that only considers the first part of the word

### ISSUE THREAD

**Issue by peterfication** [johmsalas/text-case.nvim#135]
E.g. when you have `CarScreen` and the cursor is on `Car` it will start the command `<CMD>Subs/Car/` instead of `<CMD>Subs/CarScreen/`

**Comment by johmsalas** [comment]
There is some logic I'm writing to handle more complex words as part of the multi cursor feature. Will move them to a utils file to avoid being a blocker for this one

**Comment by johmsalas** [comment]
Draft: https://github.com/johmsalas/text-case.nvim/blob/c22d4572c82a14e773a189d50b8182b2a92f8d59/lua/textcase/shared/utils.lua#L334C5-L334C5

**Comment by peterfication** [comment]
I would have just used the `cword` and then use the `to_parts` function to get the first part.

**Comment by peterfication** [comment]
See https://github.com/johmsalas/text-case.nvim/pull/137/files#diff-8aab9b62cfb84a37ff1273e1a1a51c8d84b6edf115461656d387f46d8ce787f5R396

**Comment by johmsalas** [comment]
Removed my previous comment, I assumed it was another issue, just created another enhancement issue: https://github.com/johmsalas/text-case.nvim/issues/136

@peterfication. Question: should this be another command? shall we add custom objects according to different cases? for example a custom object defining a small part of a word like oneTwoThree, if the cursor is on the word two, that could be an object itself

**Comment by peterfication** [comment]
I haven't thought of it. Most likely it makes sense to have this.

My use case for this issue was that I often have things that start with a word which I want to use for Subs.

**Comment by johmsalas** [comment]
I'd like to think more about the use case. Should it be parametrizable? like being able to specify the how many words and where to start? According to different user use cases? Can you create a discussion?

**Comment by johmsalas** [comment]
Sorry, the discussion is not necessary, it took me by surprise, let's continue in the PR
