### ISSUE TITLE
Some hints

### ISSUE THREAD

**Issue by gregorias** [johmsalas/text-case.nvim#143]
Hi, I’m creating my own utilities for case conversion (I need to support Unicode) and I noticed a few things that you could consider:

1. Neovim has `vim.fn.tolower` ([link](https://neovim.io/doc/user/builtin.html#tolower()) that you can use instead [here](https://github.com/johmsalas/text-case.nvim/blob/d6f121ec471118afb4fc7ed8cafb08eef3e9b307/lua/textcase/conversions/stringcase.lua#L68-L70). I've tried it and it seems to support non-ASCII transformations.
2. `has_lower` ([link](https://github.com/johmsalas/text-case.nvim/blob/d6f121ec471118afb4fc7ed8cafb08eef3e9b307/lua/textcase/conversions/stringcase.lua#L119)) doesn't support Unicode characters. I’m considering writing my own that uses `tolower` and then compares the two characters for equality.
3. There’s [charclass](https://neovim.io/doc/user/builtin.html#charclass()) that you can use to check if a character is punctuation or not.
4. There’s [charidx](https://neovim.io/doc/user/builtin.html#charidx()) that you can use to split a string into a character list, e.g., https://github.com/johmsalas/text-case.nvim/blob/d6f121ec471118afb4fc7ed8cafb08eef3e9b307/lua/textcase/conversions/stringcase.lua#L60-L66. Possibly it’s a more reliable way of doing it.

Keep up on the good work.

**Comment by gregorias** [comment]
Here’s how I intend to implement caseness API in my environment:

```lua
--- Extra string-related utilities.
-- @module coerce.string
local M = {}

--- Checks if a string uses only unicase characters.
--
-- A unicase character is a character that is neither upper nor lower case,
-- e.g., punctuation or Japanese kanji.
--
--@param str The string to check.
--@return True iff the string is in unicase.
M.is_unicase = function (str)
	return vim.fn.toupper(str) == vim.fn.tolower(str)
end

--- Checks if a char is in upper case.
--
--@param char The char to check.
--@return True iff the char is in upper case.
M.is_upper = function(char)
	return not M.is_unicase(char) and vim.fn.toupper(char) == char
end

--- Checks if a char is in lower case.
--
--@param char The char to check.
--@return True iff the char is in lower case.
M.is_lower = function(char)
	return not M.is_unicase(char) and not M.is_upper(char)
end

return M
```

Tests:

```
local coerce_string = require("coerce.string")

describe("coerce.string", function()
	describe("is_unicase", function()
		it("Treats punctuation as unicase.", function()
			assert.True(coerce_string.is_unicase("-,:"))
		end)
		it("Treats numbers as unicase.", function()
			assert.True(coerce_string.is_unicase("9123"))
		end)
		it("Treats kanji as unicase.", function()
			assert.True(coerce_string.is_unicase("あいうえお"))
		end)
		it("Treats alphabet as not unicase.", function()
			assert.False(coerce_string.is_unicase("ą"))
			assert.False(coerce_string.is_unicase("Ą"))
			assert.False(coerce_string.is_unicase("z"))
		end)
	end)
	describe("is_upper|is_lower", function()
		it("Should reliably check for upper caseness.", function()
			assert.True(coerce_string.is_upper("A"))
			assert.True(coerce_string.is_upper("Ą"))
			assert.False(coerce_string.is_upper("a"))
			assert.False(coerce_string.is_upper("ą"))
		end)

		it("Should mark unicase characters as neither lower nor upper case.", function()
			assert.False(coerce_string.is_upper("."))
			assert.False(coerce_string.is_lower("."))
		end)
	end)
end)
```

**Comment by gregorias** [comment]
Note: I'll probably need to change is_upper/is_lower to accept a full string to accomodate for combining characters.

**Comment by johmsalas** [comment]
Hi @gregorias, appreciate the hints
 
Unicode support has been working without issues (or may not be enough users to report them) and it has integration testing coverage. We're going to consider your suggestions if any bug comes up.

Feel free to report any bug or more hints, tbh I didn't know about the things you mentioned
