### ISSUE TITLE
When passing an empty string or nil to the api, an error will occur.

### ISSUE THREAD

**Issue by singlexyz** [johmsalas/text-case.nvim#145]
I use textcase to convert strings in luasnip, and I found that when an empty string is passed, textcase will throw an error.

```lua
-- only text to_pascal_case and to_camel_case
require('textcase').api.to_pascal_case("") // error
```

It should return an empty string.

**Comment by johmsalas** [comment]
Great use case!!, That's in fact the reason why the methods exist in an `api` namespace and there are plans to add [that feature](https://github.com/johmsalas/shake.nvim/blob/main/README.md#snip-lua) in shake.nvim (which is right now deprecated)

@singlexyz would you like to share how you use them in LuaSnip?

**Comment by johmsalas** [comment]
Created a [PR](https://github.com/johmsalas/text-case.nvim/pull/146)

**Comment by singlexyz** [comment]
> Great use case!!, That's in fact the reason why the methods exist in an `api` namespace and there were plans to add [that feature](https://github.com/johmsalas/shake.nvim/blob/main/README.md#snip-lua) in shake.nvim (which is right now deprecated)
> 
> @singlexyz would you like to share how you use them in LuaSnip?

Yeah. I have the luasnip config like this:
```
  s(
    "us",
    fmt("const [{}, {}] = useState({})", {
      i(1, "value"),
      f(function(args)
        return "set" .. textcase.api.to_pascal_case(args[1][1])
      end, { 1 }),
      i(0),
    })
  ),
```

A value is based on the input of another value and then transformed into Pascal case. 
However, after deleting the characters, textcase will throw an error and interrupt the execution of LuaSnip.

https://github.com/johmsalas/text-case.nvim/assets/4456413/fb0af327-4ac6-47b7-be93-12edf3b820c9


I can also place TextCase within a function for conditional checks.
```
local case_convert = function(str, method)
  if str == nil or str == "" then
    return ""
  end
  return textcase.api[method](str)
end
```

**Comment by johmsalas** [comment]
@singlexyz the PR was merged. Let me know how it goes

**Comment by singlexyz** [comment]
> @singlexyz the PR was merged. Let me know how it goes

Everything is works fine, that's great 😄
