### ISSUE TITLE
Subs command not available until I run a command to change text

### ISSUE THREAD

**Issue by agaro1121** [johmsalas/text-case.nvim#157]
For some reason, the "Subs" command won't show up until I run any of the {ga}{...} commands.  Is this expected behavior?

my config:

```shell
return {
  "johmsalas/text-case.nvim",
  dependencies = { "nvim-telescope/telescope.nvim" },
  keys = {
    "ga", -- Default invocation prefix
    { "ga.", "<cmd>TextCaseOpenTelescope<CR>", desc = "Teslescope", mode = {"n", "v"} },
  },
  config = function()
    require("textcase").setup({})
    require("telescope").load_extension("textcase")
  end
}

```

**Comment by peterfication** [comment]
This seems rather strange. I can't reproduce this in my setup. Also, we have extensive integration test cases with a minimal setup that work without running any of the `ga` commands first. Not sure what a next step for an investigation could be :/

**Comment by peterfication** [comment]
Are you using [LazyVim](https://www.lazyvim.org/)? It might have to do with lazy loading.

**Comment by agaro1121** [comment]
You're right. It's the lazy loading. Without specifying `lazy = false`, you get that behavior. The lazy UI also shows this:

![image](https://github.com/johmsalas/text-case.nvim/assets/2607903/88e2f7aa-c17c-4170-a44a-200063c97c96)

**Comment by agaro1121** [comment]
It also seems to work correctly (for me) if the key map is moved outside of lazy

```shell
return {
  "johmsalas/text-case.nvim",
  dependencies = { "nvim-telescope/telescope.nvim" },
  config = function()
    require("textcase").setup({})
    require("telescope").load_extension("textcase")

    vim.keymap.set({ "n", "v" }, "ga.", ":TextCaseOpenTelescope<CR>")
  end
}
```

**Comment by peterfication** [comment]
Interesting. In any case, this just seems to disable lazy loading. And disabling lazy loading is necessary for this plugin because even if we add the `Subs` command to the `cmd` config, the first usage of the `Subs` command does not work interactively because it's not loaded yet.

**Comment by agaro1121** [comment]
Agreed. Thanks for looking into this.

**Comment by johmsalas** [comment]
Looks like using `cmd` works. What is failing is the [inccommand preview](https://www.reddit.com/r/neovim/comments/wshdqf/neovim_now_has_inccommand_preview_support_for/) that is a visual indicator of the ongoing change.

From my initial research, text-case requires a small refactor splitting some files to be always loaded while keeping all the other files lazy loaded. Then, we should be able to use [Lazyvim's](https://github.com/folke/lazy.nvim?tab=readme-ov-file#-plugin-spec) `init` method to load only the initialization file

> **init:** functions are always executed during startup

https://github.com/folke/lazy.nvim?tab=readme-ov-file#-plugin-spec
