### ISSUE TITLE
FR: use Telescope or any fuzzy find tool to select case

### ISSUE THREAD

**Issue by marcelarie** [johmsalas/text-case.nvim#16]
It will be cool to open a telescope menu where any input can be passed, words, visual selections, even lsp_renames, and you can use the name of the case to fuzzy find the one that you want.

**Comment by johmsalas** [comment]
That's a good idea!. @marcelarie, would you like to give it a try? It is the branch "issue-16".
If you need some guidance on how to test a branch, let me know how you installed the plugin

https://github.com/johmsalas/text-case.nvim/pull/18

**Comment by johmsalas** [comment]
By the way, you will need to load the Telescope extension, probably inside the config method

```
require('telescope').load_extension('textcase')
```

And setup keybinding for visual and normal mode to:

```
<cmd>Telescope textcase change<CR>
```

**Comment by marcelarie** [comment]
Wow, that was quick, I will find a spot to test it this week 👍🏽 Thanks

**Comment by johmsalas** [comment]
Added support for the visual mode, this is the keymap to support both modes:

  { "johmsalas/text-case.nvim", branch="issue-16",
    config = function()
      require('textcase').setup {}
      require('telescope').load_extension('textcase')
      vim.api.nvim_set_keymap('n', 'ga.', '<cmd>TextCaseOpenTelescope<CR>', { desc = "Telescope" })
      vim.api.nvim_set_keymap('v', 'ga.', "<cmd>TextCaseOpenTelescope<CR>", { desc = "Telescope" })
    end
  }

**Comment by johmsalas** [comment]
Hi @marcelarie !

Created different commands for LSP and Quick replacement. This is my setup for testing purpose

```
      require('textcase').setup {}
      require('telescope').load_extension('textcase')
      vim.api.nvim_set_keymap('n', 'ga.', '<cmd>TextCaseOpenTelescope<CR>', { desc = "Telescope" })
      vim.api.nvim_set_keymap('v', 'ga.', "<cmd>TextCaseOpenTelescope<CR>", { desc = "Telescope" })
      vim.api.nvim_set_keymap('n', 'gaa', "<cmd>TextCaseOpenTelescopeQuickChange<CR>", { desc = "Telescope Quick Change" })
      vim.api.nvim_set_keymap('n', 'gai', "<cmd>TextCaseOpenTelescopeLSPChange<CR>", { desc = "Telescope LSP Change" })
```

I'm planning to merge it as it is, tomorrow (I'll merge it but will leave the branch so that it does not break your setup, and will remove it later in the future)

Do you think you could create a different issue for handling the behavior described in your video?

**Comment by marcelarie** [comment]
Yes, no problem. :) 

This is a nice functionality added to the project, congratulations.
