### ISSUE TITLE
Clients with `documentChanges` capability 

### ISSUE THREAD

**Issue by TinyLittleWheatley** [johmsalas/text-case.nvim#167]
I'm getting an error for `lsp_rename` in some go file.
The root of the problem is this line:
https://github.com/johmsalas/text-case.nvim/blob/d62c63a4e9a996c7321885937ab89920fca2c1c8/lua/textcase/plugin/conversion.lua#L107

Which produces this error:
```
Error executing vim.schedule lua callback: vim/shared.lua:559: t: expected table, got nil
```
This is what my `response` looks like:
```
{
  result = {
    documentChanges = { {
        edits = { {
            newText = "AlphabetError",
            range = {
              ["end"] = {
                character = 16,
                line = 18
              },
              start = {
                character = 1,
                line = 18
              }
            }
          }, {
            newText = "AlphabetError",
            range = {
              ["end"] = {
                character = 42,
                line = 105
              },
              start = {
                character = 27,
                line = 105
              }
            }
          } },
        textDocument = {
          uri = "file:///F:/something/something/validations.go",
          version = 0
        }
      } }
  }
}
```

So i took a look at [the specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit) and it seems like `changes` is an optional field of the interface and the edits might be on the `documentChanges` field based on the client capabilities.
I propose:
```lua
          local files_count_by_current_response
          if response.result.changes ~= nil then
            files_count_by_current_response = vim.tbl_count(response.result.changes)
          else
            files_count_by_current_response = vim.tbl_count(response.result.documentChanges)
          end
```

Should i make a pr?

**Comment by Aphosis** [comment]
I also had this issue for a while (in Python buffers) and found this issue, the suggested patch worked great for me, thanks a lot !

**Comment by johmsalas** [comment]
Good catch!, @TinyLittleWheatley could you please create that PR? [This is an example](https://github.com/johmsalas/text-case.nvim/blob/d62c63a4e9a996c7321885937ab89920fca2c1c8/tests/textcase/lsp/error_handling_no_lsp_spec.lua#L193) of how response.result.changes was mocked in the unit tests

**Comment by TinyLittleWheatley** [comment]
@johmsalas, I made the PR with mentioned changes. It doesn't change the unit tests though. I assume I should add a unit test that mocks the LSP behavior that caused the issue... right?

**Comment by TinyLittleWheatley** [comment]
Thanks for the direction🙃. 
I've added the second unit test provided in your example but the first one seems kind of tricky to me. We don't really decide which field has to be applied... We choose one result object based on number of changes they make and pass it as is. Anyways the code is modified to count `documentChanges` instead of `changes` if both are available.

Also the documentation says(just before the sentence you quoted) that one of these fields(either ... or ...) should be set on result which confuses me.

**Comment by johmsalas** [comment]
This is merged :fireworks:. The added test is enough, I adjusted the commit message to adhere to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

Thank you so much for your contribution 😁
