### ISSUE TITLE
Edge case with `to_snake_case` not working correctly

### ISSUE THREAD

**Issue by aMOPel** [johmsalas/text-case.nvim#22]
Thanks for this great plugin :)

**Reproduce Bug:**

```txt
# test.txt
template backendError(tTasks: R, body: untyped) =
  if tTasks.isErr:
    stderr.writeLine conf.backend & " backend error: " & tTasks.error
    body
```

use `gas` (`require('textcase').current_word('to_snake_case')`) on every occurence of `tTasks`:

```txt
# text.txt
template backendError(t_tasks: R, body: untyped) =
  ift_tasks.isErr:
    stderr.writeLine conf.backend & " backend error: " &t_tasks.error
    body
```

as you can see the conversion to snake case filled the space before the `tTasks` in 2 out of 3 cases. This breaks the syntax in this particular case.

**Expected behavior:**

The converted text gets shifted to the right in all cases.

**Comment by johmsalas** [comment]
That's interesting. I will take a look 

Does the LSP version work on this case?

**Comment by aMOPel** [comment]
> Does the LSP version work on this case?

Nope. But that's to be expected. This is Nim code and the Nim lsp rename is not working properly.

I tested this example in a `.nim` file as well as in a `.txt` file, getting the same result. Naturally in the `.txt` file there was no lsp attached.

**Comment by johmsalas** [comment]
Hi! 

I'm back from vacations and was able to reproduce it. 

[This PR](https://github.com/johmsalas/text-case.nvim/pull/25/files) should solve the issue. Added a [unit test](https://github.com/johmsalas/text-case.nvim/blob/99870c444f1b22ec62c69d875e3b9aad004729c9/tests/textcase/conversions/stringcase_spec.lua#L206) with your example

I'll be using it for the next days before merging to `main`, if you want to have this fix, and be an early tester :), you can pull the branch issue-22

**Comment by johmsalas** [comment]
This was merged now. Thanks for reporting
