### ISSUE TITLE
Conversion happens on all text, not on selection

### ISSUE THREAD

**Issue by kontza** [johmsalas/text-case.nvim#29]
Hi,

I'm trying to convert my workflow from VS Code world to Neovim. The following is a regular use-case for me in VS Code: I select a rectangular area of text, then run a case converter from command palette. 

I tried to do the same in with Neovim + textcase. I have mapped 'ga.' to open the telescope extension. See the following video:
https://user-images.githubusercontent.com/2431112/194544178-c076f473-cc4d-4f53-b4d6-faaedb8e0cc1.mov

The order of operations in the video is:
1. Select a block.
2. 'ga.' to have the popup open.
3. Select snake case.

To my surprise, all text was converted to snake case, not only the selected block.

**Comment by johmsalas** [comment]
Hi @kontza,

What command are you using for mapping `ga.` to Telescope? Unfortunately the regular `:Telescope <command>` does not work because the visual mode is dropped. So, should be `<cmd>TextCaseOpenTelescope<CR>` instead

**Comment by johmsalas** [comment]
Oh, actually, when I tested for this issue, it worked, but now I was able to reproduce it. I noticed it only happens with the Telescope option, as a workaround, mapping the conversion directly does work

`nnoremap gac :lua require('textcase').current_word('to_camel_case')<CR>`

Will have a look into the issue. thanks for reporting

**Comment by kontza** [comment]
Ok, thanks for the tip above.

And to answer your question about mappings: this is how I have mapped `ga.`: 
```
vim.api.nvim_set_keymap('n', 'ga.', 
    '<cmd>TextCaseOpenTelescope<CR>', 
    { desc = "Telescope" })
vim.api.nvim_set_keymap('v', 'ga.',
    '<cmd>TextCaseOpenTelescope<CR>',
    { desc = "Telescope" })
```

**Comment by peterfication** [comment]
@kontza did my fix solve your problem? Can you please test with the latest version?

**Comment by kontza** [comment]
Yup, it works. Cheers!
