### ISSUE TITLE
Visual line mode still not scoping properly

### ISSUE THREAD

**Issue by nianiam** [johmsalas/text-case.nvim#35]
Visual block mode works great. However, visual line mode's scoping is inconsistent. It seems to depend upon where the cursor is placed at the start and end of the visual selection. Here's a video example:

https://user-images.githubusercontent.com/70338628/214253328-1693fcbb-8077-4b37-9cd1-c03f077f956a.mp4

I have tree sitter with the relevant language installed if that's any use. Unfortunately, I haven't managed to figure out any patterns during use.

**Comment by peterfication** [comment]
@nianiam this issue might have been fixed by https://github.com/johmsalas/text-case.nvim/pull/83 or https://github.com/johmsalas/text-case.nvim/pull/85

Can you please test it again?

@dusty-phillips can you try as well?

**Comment by peterfication** [comment]
Closing this as no more issues were reported here.
