### ISSUE TITLE
:Subs seems to be buggy

### ISSUE THREAD

**Issue by j-hui** [johmsalas/text-case.nvim#36]
I have a text file containing the following:

```
a
```

If I run `:Subs/a/aa`, I get:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Comment by j-hui** [comment]
When running `:Subs/<from>/<to>`, the problem seems to occur when `<to>` is a substring of `<from>`

**Comment by peterfication** [comment]
This has been fixed by another fix. However, https://github.com/johmsalas/text-case.nvim/pull/91 adds a dedicated test case for it.
