### ISSUE TITLE
In visual mode, converting selected text has error

### ISSUE THREAD

**Issue by erm1116** [johmsalas/text-case.nvim#37]
I got an error when starting visual mode from a end character and converting text.
Here is the capture.

https://user-images.githubusercontent.com/38889285/217829723-1d3cff48-1153-4bd1-be3c-ccbda93717d7.mp4

Error message is as below:
```text
E5108: Error executing lua /path/to/textcase/plugin/conversion.lua:38: start is higher than end
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        /path/to/textcase/plugin/conversion.lua:38: in function 'do_substitution'
        /path/to/textcase/plugin/plugin.lua:229: in function </path/to/textcase/plugin/plugin.lua:191>
```

**Comment by johmsalas** [comment]
It hadn't been solved due to missing automated tests, but they now exist. I'd like to show my appreciation to @peterfication for making this plugin more stable
