### ISSUE TITLE
Fixing the additional 'o' for operator-pending mode is clumsy

### ISSUE THREAD

**Issue by andrewferrier** [johmsalas/text-case.nvim#4]
`text-mode` seems great so far. However, personally I find the additional 'o' for the operator-pending mode a bit clumsy; it makes the keybinding one extra key for no reason.

I believe I would only ever use the operator-pending mode, and would prefer to have a completely separate prefix key for this than for the normal/visual mode prefixes. It would be great if I could configure that independently.

Thanks!

**Comment by johmsalas** [comment]
Hi @andrewferrier 

Just added examples with custom key mapping in the readme
