### ISSUE TITLE
Bug: all current word commands error

### ISSUE THREAD

**Issue by chrisgrieser** [johmsalas/text-case.nvim#40]
```lua
Keymap("n", "cru", ":lua require('textcase').current_word('to_upper_case')<CR>", { desc = "UPPER CASE" })
```
(also happens with default mappings and with any other casing though)

![Pasted image 2023-04-04 at 19-57-16 of Userschrisgrieser confignvimluaconfigoptions-and-autocmds lua@2x](https://user-images.githubusercontent.com/73286100/229879161-72e31c82-c487-4cff-8fce-f453db213b0f.png)

**Comment by chrisgrieser** [comment]
just checked, using the previous commit [2cbe6b6](https://github.com/johmsalas/text-case.nvim/commit/2cbe6b6653b46d2ec23bb2ba808b5c1fc78e9382) works fine, so it seems to be an issue introduced by the last commit

**Comment by johmsalas** [comment]
Hi @chrisgrieser! Thanks for the report. I haven't coded much lately so I didn't notice it. 

Do you think you can create a PR? I think it should be something like:

```lua
desc = method and method(desc) or desc,
```

Since you already identified the commit I think you have the development setup. Othewise let me know and I can help.
Thanks again

**Comment by chrisgrieser** [comment]
oh, just noticed that the last commit breakings things is literally just a one-line-change, making the fix very straight-forward 😛 

okay, opened PR for the fix

**Comment by mmirus** [comment]
:wave: Sorry about that, @chrisgrieser. I didn't experience this bug (using any of the default mappings). I can reproduce it by running `:lua require('textcase').current_word('to_upper_case')`, though.

Hopefully there's a fairly simple way to get the nice mapping descriptions out of the box, but in the meanwhile obviously better to revert that and keep all the real functionality working.
