### ISSUE TITLE
:Subs for visual selection is buggy

### ISSUE THREAD

**Issue by mollerhoj** [johmsalas/text-case.nvim#44]
It doesn't make replacement in all lines. I think it might have something to do with how long the lines are? Full file replacement works.

**Comment by peterfication** [comment]
We recently added tests to this repository. For the `Subs` command, we just have one test so far which works fine. I opened a draft PR to add another test for visual block mode and it also works fine: https://github.com/johmsalas/text-case.nvim/pull/82/files

I tried with a longer line locally and it also worked.

Could @mollerhoj, @cenk1cenk2 or @mactep provide me with an example so I can get a failing test?

**Comment by cenk1cenk2** [comment]
It works a hundred times better for me with the latest patches. At some point, it started to work for me properly, I can't pinpoint the exact commit.

The only issue while using Subs command is if you have the original entry as the substring of the newer entry, it repeats the last words. But I have seen there was another issue open on that.

To give an example
```
  // join-column -> from service_category
  @ApiProperty({
    type: String,
    readOnly: true,
    nullable: true
  })
  @IsUUID()
  @Column({ name: 'service_category_id', type: DATABASE_PRIMARY_COLUMN_TYPE })
    serviceCategoryId: ServiceCategoryEntity['id']

  @ApiProperty({
    type: () => ServiceCategoryEntity,
    readOnly: true
  })
  @JoinColumn({ name: 'service_category_id' })
  @ManyToOne(() => ServiceCategoryEntity, (serviceCategory) => serviceCategory.bookings, { onDelete: 'SET NULL' })
    serviceCategory?: ServiceCategoryEntity

```
Will yield in
![image](https://github.com/johmsalas/text-case.nvim/assets/26881592/7450d9c0-e822-48c1-8ed1-cb1b001f0c29)
where last word is repeated.

But other than that thank you so much for your work on it last updates have solved the issues for me, I will post a test case if I find a failing one again.

**Comment by peterfication** [comment]
Glad things improved for you :)

I created a separate ticket for what you were describing, because it's a different bug I would assume: https://github.com/johmsalas/text-case.nvim/issues/84

**Comment by peterfication** [comment]
Closing this as no more issues were reported here.
