### ISSUE TITLE
How to register only a subset of default keybindings?

### ISSUE THREAD

**Issue by fuelen** [johmsalas/text-case.nvim#45]
And the same question about `TextCaseOpenTelescopeQuickChange`. I'm not interested in all the combinations.

**Comment by peterfication** [comment]
This plugin registers itself without the need to call the `setup` function.

The README states:

```
Install with your favorite plugin manager. The setup function, sets up the default keybinding. To setup custom key maps, do not call require('textcase').setup{}, and follow the example bellow
```

I agree that this is not obvious from the setup call itself, as this call has no options.

For the Telescope use case, I'm not sure whether we should support disabling certain conversions as Telescope is a fuzzy finder, so having all conversions in there is not that big of a deal. But I will think about it.

**Comment by fuelen** [comment]
> I'm not sure whether we should support disabling certain conversions as Telescope

The reason why I'm asking about this is that I really don't need all the conversions, as for the language I usually work with I need only camel case and snake case. Everything else is a visual noise. The same is true about Which key integration. Too many variants and I lose myself when I'm trying to find what I need.

**Comment by peterfication** [comment]
The Telescope use case can only be tackled after we have integration tests for it: https://github.com/johmsalas/text-case.nvim/issues/62

**Comment by peterfication** [comment]
The methods for which-key can now be configured. For Telescope, there is another issue: https://github.com/johmsalas/text-case.nvim/issues/92

**Comment by peterfication** [comment]
The Telescope feature is now available as well
