### ISSUE TITLE
Disable entirely the automatic configuration of keymappings?

### ISSUE THREAD

**Issue by andrewferrier** [johmsalas/text-case.nvim#5]
It would be nice for more advanced users to map their own keybindings. For example, I'm not really interested in the normal mode mappings, and would like to just remove them. Also, some of the 'more obscure' cases like path case don't have their own mapping out of the box, but I would like to add one. Some examples of how to do that would be helpful.

**Comment by johmsalas** [comment]
Hi! Just merged a PR. "calling setup()" is not anymore a requirement. 

What plugin manager do you use?
I tried with Plug, so that I can have better understanding of users different use cases

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'johmsalas/text-case.nvim'
call plug#end()

nnoremap gau :lua require('textcase').current_word('to_upper_case')<CR> 
```

Can you take a look if this works for you? then I can update the documentation

**Comment by andrewferrier** [comment]
Wonderful, this works well, thank you!
