### ISSUE TITLE
Add Integration Tests: Telescope in Normal Mode

### ISSUE THREAD

**Issue by johmsalas** [johmsalas/text-case.nvim#62]

**Comment by peterfication** [comment]
When I was fiddling around with my local Neovim version, I saw that Telescope requires Neovim version 0.9.0. So when tests are added, they need to be excluded from Neovim version 0.8.3 runs and we need to state this in the README. Maybe a table with version and feature compatibilities could make sense.

**Comment by johmsalas** [comment]
It's becoming complicated xD
At least we don't need to tests OS... right?

**Comment by peterfication** [comment]
Yeah, I would say, testing for different OS is out-of-scope ^^

**Comment by johmsalas** [comment]
@peterfication now that you mention feature compatibility, FYI, there are some feature flags https://github.com/johmsalas/text-case.nvim/blob/65fcc8fb79ceef644af6861558bb534562ef6c0e/lua/textcase/plugin/plugin.lua#L4C7-L4C31

**Comment by peterfication** [comment]
Ah good to know!

**Comment by johmsalas** [comment]
https://github.com/johmsalas/text-case.nvim/pull/77
