### ISSUE TITLE
Add integration tests: Whichkey

### ISSUE THREAD

**Issue by johmsalas** [johmsalas/text-case.nvim#73]

**Comment by peterfication** [comment]
Not sure if we need tests for Whichkey, as we just use the normal vim keymap and Whichkey picks it up. wdyt?

**Comment by johmsalas** [comment]
Agree. I was hesitating due to an old incident.
After some investigation, if the which-key plugin was not installed the plugin would error. There are already tests for no plugins setup covering that case
