### ISSUE TITLE
Add Integration Tests: Telescope in Visual Mode

### ISSUE THREAD

**Issue by johmsalas** [johmsalas/text-case.nvim#75]

**Comment by peterfication** [comment]
Partially done in https://github.com/johmsalas/text-case.nvim/pull/99

**Comment by johmsalas** [comment]
> Partially done in https://github.com/johmsalas/text-case.nvim/pull/99

Is there something missing 🤔 ?
I wanted to be sure the visual mode was kept when using Telescope, and that is happening, shall this issue be closed?

**Comment by johmsalas** [comment]
> Partially done in https://github.com/johmsalas/text-case.nvim/pull/99

@peterfication do you think there is something missing 🤔 ?
I wanted to be sure the visual mode was kept when using Telescope, and that is happening, shall this issue be closed?

**Comment by peterfication** [comment]
I added another test for full visual lines (using `V` instead of `v`) and then it should be fine: https://github.com/johmsalas/text-case.nvim/pull/120
