### ISSUE TITLE
Error message when start nvim without install whichkey plugin.

### ISSUE THREAD

**Issue by katinbox** [johmsalas/text-case.nvim#9]
Thanks for your plugin, it working like a charm, but after I update, It show me error message because I don't using which-key plugin. So, you  can check it if it really is a bug. And sorry for my bad English :)

**Comment by johmsalas** [comment]
oh wow, I did test it but must've missing. What error does it show @katinbox ?

I'm not also a native English speaker :)

**Comment by katinbox** [comment]
Oh! When I reinstall plugin, the error message not show again

**Comment by johmsalas** [comment]
I'm setting up Docker so that I can have a env without which-key and other integrations
glad it works 👍
